### ISSUE TITLE
Create layered project example

### ISSUE THREAD

**Issue by bacpac** [wearetriple/dotnet-defaults#8]
For example, with Web, Business & Gateway projects + perhaps an extra project for a service layer.

Simple case, Regular case, Complex case.

**Comment by ThomasBleijendaal** [comment]
To get the discussion started.

# Our layered project rules:

- The name of the solution is {Customer}.{Project}.sln.
- Put simple, solution-wide used objects like enums, exceptions and simple classes in Core: {Customer}.{Project}.Core.csproj
- Put everything that has to do with an external API of which the project is client of in a Gateway class: {Customer}.{Project}.Gateway.{External API}.cspoj
- If the project exposes an API using ASP.NET Core Web Api, create a project for it called {Customer}.{Project}.Api.csproj
- If the project uses Azure Functions, create a project for those functions called {Customer}.{Project}.Functions.csproj
- Put all general business logic in {Customer}.{Project}.Business.csproj
- If the project is foreseen to contain a lot of business logic, split the business logic up into parts and give each part a separate project: {Customer}.{Project}.Business.Users.csproj, {Customer}.{Project}.Business.Payment.csproj
- If the project uses other (web) applications that do more than just an API, put them in a project that bests describes their functionality, like {Customer}.{Project}.Cms.csproj
- Put everything that has to do with the persistence layer in a separate project and use name that describes what it persists {Customer}.{Project}.Data.csproj (for all data) or {Customer}.{Project}.Data.User.csproj (for just user related data)
- Unit tests only test a specific project, and should always be called {ProjectToTest}.Tests.csproj

Example:

Contoso.CalendarHub.sln
- Contoso.CalendarHub.Api.cspoj
- Contoso.CalendarHub.Business.csproj
- Contoso.CalendarHub.Business.Tests.csproj
- Contoso.CalendarHub.Core.csproj
- Contoso.CalendarHub.Cms.csproj
- Contoso.CalendarHub.Data.Users.csproj
- Contoso.CalendarHub.Data.Invitations.csproj
- Contoso.CalendarHub.Functions.csproj
- Contoso.CalendarHub.Gateway.Adyen.csproj
- Contoso.CalendarHub.Gateway.GoogleCalendar.csproj
- Contoso.CalendarHub.Gateway.GoogleCalendar.Tests.csproj
- Contoso.CalendarHub.Gateway.OutlookCalendar.csproj
- Contoso.CalendarHub.Gateway.OutlookCalendar.Tests.csproj

# General concepts about models:

- An API always has its own Request- and ResponseModels. These models describe the exact shape of requests it expects and responses it generates.
- The Core projects contains data transfer objects (DTOs) which facilitate communication between parts of the application.
- An Gateway always has its on models. These models describe what data must be passed into the gateway and what data comes out of the gateway. The gateway exposes an interface which accepts and returns DTOs.
- The persistence layer uses its own entities to store data in a database or other storage, and exposes an interface which accepts and returns DTOs.
- Business logic uses DTOs.

Example:

A payment request is made to the projects API controller, receiving an `AddPaymentRequestModel`. The API validates whether the request is valid (using data annotations on the model, or FluentValidation for that model). If the request is valid, the API controller transform the model to `AddPaymentDto` and passes it to `IPaymentService`. The implementer of this interface can opt to validate `AddPaymentDto`, but can also assume its validity. The service talks to `IPaymentGateway` which accepts the `AddPaymentDto`, converts it to `AdyenCreatePaymentModel` and sends it to the payment provider. The payment provider returns `PaymentModel`, which is converted to `PaymentDetailsDto` which is returned by the `IPaymentGateway`. The payment service uses that dto to talk to the `IPaymentRepository` to save the payment. That repository converts the `PaymentDetailsDto` to `PaymentEntity` which is persisted in the database.

Each part has their own models for their own logic, isolating each part. A change in the shape of API's `AddPaymentRequestModel` will not force other services and interfaces to change. This makes updating the entire application more easy. This way of working involves a lot of mapping between objects. A setup where these mappings are automatically generated is advisable and the use of things like AutoMapper, ExpressionMapper or GeneratedMapper is encouraged.

**Comment by bacpac** [comment]
@ThomasBleijendaal 
Agreed with all of the above; except not entirely sure about the DTOs being used in the Business layer. 

I believe DTO's are used as input / output model of your project, as they only transfer data to and from your application in some transfer efficient format (most of the time dependent on other parties). Inside your business layer you are dealing with Domain models (or Bussiness Objects), where your concept of a model is complete / correct in how you use it in your internal eco system of a project.

Further reading can be found here:
https://en.wikipedia.org/wiki/Data_transfer_object

**Comment by ThomasBleijendaal** [comment]
Agreed, perhaps the naming should be different. I'll rearrange the names a bit and move these examples to a PR.
